//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSampleWitEF.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDBCtx : DbContext //DbContext - Klasse -> EF 6.0 
        //In EF 5.0 anstatt DbContext-Basisklasse -> ObjectContext

    {
        public MovieDBCtx()
            : base("name=MovieDBCtx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movie { get; set; } //DbSet -> ist eine Tabelle in ObjectForm
    }
}
